Test buildjet speeds

diff --git a/.github/workflows/staticbuild.yml b/.github/workflows/staticbuild.yml
--- a/.github/workflows/staticbuild.yml
+++ b/.github/workflows/staticbuild.yml
@@ -20,7 +20,31 @@ jobs:
           - arch: [x64, qemu-host]
             image: ghcr.io/viamrobotics/antique:amd64-cache
             platform: linux/amd64
+          - arch: buildjet-2vcpu-ubuntu-2204
+            image: ghcr.io/viamrobotics/antique:amd64-cache
+            platform: linux/amd64
+          - arch: buildjet-4vcpu-ubuntu-2204
+            image: ghcr.io/viamrobotics/antique:amd64-cache
+            platform: linux/amd64
+          - arch: buildjet-8vcpu-ubuntu-2204
+            image: ghcr.io/viamrobotics/antique:amd64-cache
+            platform: linux/amd64
+          - arch: buildjet-16vcpu-ubuntu-2204
+            image: ghcr.io/viamrobotics/antique:amd64-cache
+            platform: linux/amd64
           - arch: [arm64, qemu-host]
+            image: ghcr.io/viamrobotics/antique:arm64-cache
+            platform: linux/arm64
+          - arch: buildjet-2vcpu-ubuntu-2204-arm
+            image: ghcr.io/viamrobotics/antique:arm64-cache
+            platform: linux/arm64
+          - arch: buildjet-4vcpu-ubuntu-2204-arm
+            image: ghcr.io/viamrobotics/antique:arm64-cache
+            platform: linux/arm64
+          - arch: buildjet-8vcpu-ubuntu-2204-arm
+            image: ghcr.io/viamrobotics/antique:arm64-cache
+            platform: linux/arm64
+          - arch: buildjet-16vcpu-ubuntu-2204-arm
             image: ghcr.io/viamrobotics/antique:arm64-cache
             platform: linux/arm64
     runs-on: ${{ matrix.arch }}
@@ -81,106 +105,107 @@ jobs:
       run: |
         sudo -Hu testbot bash -lc 'make RELEASE_TYPE="${{ inputs.release_type }}" BUILD_CHANNEL="${{ github.ref_name }}" static-release'
 
-    - name: Set Date
-      id: build_date
-      run: echo "date=`date +%F`" >> $GITHUB_OUTPUT
+  # SMURF
+  #   - name: Set Date
+  #     id: build_date
+  #     run: echo "date=`date +%F`" >> $GITHUB_OUTPUT
 
-    - name: Upload Files (Testing)
-      if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
-      uses: google-github-actions/upload-cloud-storage@v0.10.4
-      with:
-        headers: "cache-control: no-cache"
-        path: 'etc/packaging/static/deploy/'
-        destination: 'packages.viam.com/apps/viam-server/testing/static/${{ steps.build_date.outputs.date }}/${{ github.sha }}/'
-        glob: 'viam-server-*'
-        parent: false
-        gzip: false
+  #   - name: Upload Files (Testing)
+  #     if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
+  #     uses: google-github-actions/upload-cloud-storage@v0.10.4
+  #     with:
+  #       headers: "cache-control: no-cache"
+  #       path: 'etc/packaging/static/deploy/'
+  #       destination: 'packages.viam.com/apps/viam-server/testing/static/${{ steps.build_date.outputs.date }}/${{ github.sha }}/'
+  #       glob: 'viam-server-*'
+  #       parent: false
+  #       gzip: false
 
-  output_summary:
-    name: Output Summary
-    runs-on: ubuntu-latest
-    needs: static
-    if: contains(github.event.pull_request.labels.*.name, 'static-build') || contains(github.event.pull_request.labels.*.name, 'static-ignore-tests')
-    steps:
-    - name: Output Summary
-      run: |
-        channel="pr-${{ github.event.pull_request.number }}"
-        echo "### Built Static Binaries for ${channel}" >> $GITHUB_STEP_SUMMARY
-        echo "- arm64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-aarch64" >> $GITHUB_STEP_SUMMARY
-        echo "- x86_64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-x86_64" >> $GITHUB_STEP_SUMMARY
-        echo "" >> $GITHUB_STEP_SUMMARY
+  # output_summary:
+  #   name: Output Summary
+  #   runs-on: ubuntu-latest
+  #   needs: static
+  #   if: contains(github.event.pull_request.labels.*.name, 'static-build') || contains(github.event.pull_request.labels.*.name, 'static-ignore-tests')
+  #   steps:
+  #   - name: Output Summary
+  #     run: |
+  #       channel="pr-${{ github.event.pull_request.number }}"
+  #       echo "### Built Static Binaries for ${channel}" >> $GITHUB_STEP_SUMMARY
+  #       echo "- arm64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-aarch64" >> $GITHUB_STEP_SUMMARY
+  #       echo "- x86_64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-x86_64" >> $GITHUB_STEP_SUMMARY
+  #       echo "" >> $GITHUB_STEP_SUMMARY
 
-  static_test:
-    name: Static Test
-    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
-    strategy:
-      matrix:
-        arch: [[x64, qemu-host], [arm64, qemu-host], [arm64, pi4]]
-    needs: static
-    runs-on: ${{ matrix.arch }}
-    timeout-minutes: 15
-    outputs:
-      date: ${{ needs.static.outputs.date }}
+  # static_test:
+  #   name: Static Test
+  #   if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
+  #   strategy:
+  #     matrix:
+  #       arch: [[x64, qemu-host], [arm64, qemu-host], [arm64, pi4]]
+  #   needs: static
+  #   runs-on: ${{ matrix.arch }}
+  #   timeout-minutes: 15
+  #   outputs:
+  #     date: ${{ needs.static.outputs.date }}
 
-    steps:
-    - name: Clean Workspace
-      run: |
-        shopt -s dotglob
-        sudo chown -R `whoami` ./
-        rm -rf ./*
+  #   steps:
+  #   - name: Clean Workspace
+  #     run: |
+  #       shopt -s dotglob
+  #       sudo chown -R `whoami` ./
+  #       rm -rf ./*
 
-    - name: Test Static Binary
-      run: |
-        channel="${{ github.ref_name }}"
-        # we call our main branch releases "latest"
-        if [ "$channel" = "main" ]; then
-          channel="latest"
-        fi
+  #   - name: Test Static Binary
+  #     run: |
+  #       channel="${{ github.ref_name }}"
+  #       # we call our main branch releases "latest"
+  #       if [ "$channel" = "main" ]; then
+  #         channel="latest"
+  #       fi
 
-        export TEST_DIR=`mktemp -d -t test-viam-server-XXXXXX`
-        cd $TEST_DIR
+  #       export TEST_DIR=`mktemp -d -t test-viam-server-XXXXXX`
+  #       cd $TEST_DIR
 
-        curl -o viam-server https://storage.googleapis.com/packages.viam.com/apps/viam-server/testing/static/${{ needs.static.outputs.date }}/${{ github.sha }}/viam-server-${channel}-`uname -m`
-        chmod 755 viam-server
+  #       curl -o viam-server https://storage.googleapis.com/packages.viam.com/apps/viam-server/testing/static/${{ needs.static.outputs.date }}/${{ github.sha }}/viam-server-${channel}-`uname -m`
+  #       chmod 755 viam-server
 
-        export RAND_PORT=$((30000 + $RANDOM))
-        echo "{\"network\": {\"bind_address\":\"localhost:${RAND_PORT}\"}}" > test.json
+  #       export RAND_PORT=$((30000 + $RANDOM))
+  #       echo "{\"network\": {\"bind_address\":\"localhost:${RAND_PORT}\"}}" > test.json
 
-        ./viam-server -config test.json &
-        curl --retry 5 --retry-delay 5 --retry-connrefused localhost:$RAND_PORT
-        export RET1=$?
-        kill %%
-        wait $!
-        export RET2=$?
-        cd - && rm -rf $TEST_DIR
-        [ $RET1 == 0 ] && [ $RET1 == 0 ]
+  #       ./viam-server -config test.json &
+  #       curl --retry 5 --retry-delay 5 --retry-connrefused localhost:$RAND_PORT
+  #       export RET1=$?
+  #       kill %%
+  #       wait $!
+  #       export RET2=$?
+  #       cd - && rm -rf $TEST_DIR
+  #       [ $RET1 == 0 ] && [ $RET1 == 0 ]
 
-  static_deploy:
-    name: Static Deploy
-    needs: static_test
-    runs-on: ubuntu-latest
+  # static_deploy:
+  #   name: Static Deploy
+  #   needs: static_test
+  #   runs-on: ubuntu-latest
 
-    steps:
-    - name: Authorize GCP
-      uses: google-github-actions/auth@v1
-      with:
-        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
+  #   steps:
+  #   - name: Authorize GCP
+  #     uses: google-github-actions/auth@v1
+  #     with:
+  #       credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
 
-    - name: Set up Cloud SDK
-      uses: google-github-actions/setup-gcloud@v1
+  #   - name: Set up Cloud SDK
+  #     uses: google-github-actions/setup-gcloud@v1
 
-    - name: Publish Static Binary
-      run: |
-        gsutil mv "gs://packages.viam.com/apps/viam-server/testing/static/${{ needs.static_test.outputs.date }}/${{ github.sha }}/*" "gs://packages.viam.com/apps/viam-server/"
+  #   - name: Publish Static Binary
+  #     run: |
+  #       gsutil mv "gs://packages.viam.com/apps/viam-server/testing/static/${{ needs.static_test.outputs.date }}/${{ github.sha }}/*" "gs://packages.viam.com/apps/viam-server/"
 
-    - name: Output Summary
-      run: |
-        channel="${{ github.ref_name }}"
-        # we call our main branch releases "latest"
-        if [ "$channel" == "main" ]; then
-          channel="latest"
-        fi
-        echo "### Built Static Binaries for ${channel}" >> $GITHUB_STEP_SUMMARY
-        echo "- arm64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-aarch64" >> $GITHUB_STEP_SUMMARY
-        echo "- x86_64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-x86_64" >> $GITHUB_STEP_SUMMARY
-        echo "" >> $GITHUB_STEP_SUMMARY
+  #   - name: Output Summary
+  #     run: |
+  #       channel="${{ github.ref_name }}"
+  #       # we call our main branch releases "latest"
+  #       if [ "$channel" == "main" ]; then
+  #         channel="latest"
+  #       fi
+  #       echo "### Built Static Binaries for ${channel}" >> $GITHUB_STEP_SUMMARY
+  #       echo "- arm64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-aarch64" >> $GITHUB_STEP_SUMMARY
+  #       echo "- x86_64: https://storage.googleapis.com/packages.viam.com/apps/viam-server/viam-server-${channel}-x86_64" >> $GITHUB_STEP_SUMMARY
+  #       echo "" >> $GITHUB_STEP_SUMMARY
