minimal test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -13,102 +13,102 @@ env:
   MONGODB_TEST_OUTPUT_URI: ${{ secrets.MONGODB_TEST_OUTPUT_URI }}
 
 jobs:
-  test_go:
-    # note: we have automations that match on platform_name. be careful changing this.
-    name: ${{ matrix.platform_name }} Go Unit Tests
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - arch: ubuntu-16-core
-            image: ghcr.io/viamrobotics/rdk-devenv:amd64-cache
-            platform: linux/amd64
-            platform_name: linux-amd64
-          - arch: ubuntu-arm-16-core
-            image: ghcr.io/viamrobotics/rdk-devenv:arm64-cache
-            platform: linux/arm64
-            platform_name: linux-arm64
-    runs-on: ${{ matrix.arch }}
-    container:
-      image: ${{ matrix.image }}
-      options: --platform ${{ matrix.platform }}
-    timeout-minutes: 30
+  # test_go:
+  #   # note: we have automations that match on platform_name. be careful changing this.
+  #   name: ${{ matrix.platform_name }} Go Unit Tests
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       include:
+  #         - arch: ubuntu-16-core
+  #           image: ghcr.io/viamrobotics/rdk-devenv:amd64-cache
+  #           platform: linux/amd64
+  #           platform_name: linux-amd64
+  #         - arch: ubuntu-arm-16-core
+  #           image: ghcr.io/viamrobotics/rdk-devenv:arm64-cache
+  #           platform: linux/arm64
+  #           platform_name: linux-arm64
+  #   runs-on: ${{ matrix.arch }}
+  #   container:
+  #     image: ${{ matrix.image }}
+  #     options: --platform ${{ matrix.platform }}
+  #   timeout-minutes: 30
 
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.event.ref }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.event.ref }}
 
-      - name: Set main env vars
-        if: github.event_name != 'pull_request_target'
-        run: |
-          echo "GITHUB_X_HEAD_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
-          echo "GITHUB_X_HEAD_REF=${GITHUB_REF_NAME}" >> $GITHUB_ENV
+  #     - name: Set main env vars
+  #       if: github.event_name != 'pull_request_target'
+  #       run: |
+  #         echo "GITHUB_X_HEAD_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
+  #         echo "GITHUB_X_HEAD_REF=${GITHUB_REF_NAME}" >> $GITHUB_ENV
 
-      - name: Set PR env vars
-        if: github.event_name == 'pull_request_target'
-        env:
-          GITHUB_HEAD_REF_SAN: ${{ github.event.pull_request.head.label }}
-        run: |
-          echo "GITHUB_X_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
-          echo "GITHUB_X_HEAD_REF=${GITHUB_HEAD_REF_SAN}" >> $GITHUB_ENV
-          echo "GITHUB_X_PR_BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
-          echo "GITHUB_X_PR_BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
+  #     - name: Set PR env vars
+  #       if: github.event_name == 'pull_request_target'
+  #       env:
+  #         GITHUB_HEAD_REF_SAN: ${{ github.event.pull_request.head.label }}
+  #       run: |
+  #         echo "GITHUB_X_HEAD_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
+  #         echo "GITHUB_X_HEAD_REF=${GITHUB_HEAD_REF_SAN}" >> $GITHUB_ENV
+  #         echo "GITHUB_X_PR_BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
+  #         echo "GITHUB_X_PR_BASE_REF=${{ github.event.pull_request.base.ref }}" >> $GITHUB_ENV
 
-      - name: Chown
-        run: chown -R testbot:testbot .
+  #     - name: Chown
+  #       run: chown -R testbot:testbot .
 
-      - name: Run go unit tests
-        run: |
-          chmod -R a+rwx . # temporary fix for arm runners
-          sudo apt-get update && sudo apt-get install -y python3-venv
-          sudo --preserve-env=MONGODB_TEST_OUTPUT_URI,GITHUB_SHA,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_RUN_ATTEMPT,GITHUB_X_PR_BASE_SHA,GITHUB_X_PR_BASE_REF,GITHUB_X_HEAD_REF,GITHUB_X_HEAD_SHA,GITHUB_REPOSITORY -Hu testbot bash -lc 'make test-go'
+  #     - name: Run go unit tests
+  #       run: |
+  #         chmod -R a+rwx . # temporary fix for arm runners
+  #         sudo apt-get update && sudo apt-get install -y python3-venv
+  #         sudo --preserve-env=MONGODB_TEST_OUTPUT_URI,GITHUB_SHA,GITHUB_RUN_ID,GITHUB_RUN_NUMBER,GITHUB_RUN_ATTEMPT,GITHUB_X_PR_BASE_SHA,GITHUB_X_PR_BASE_REF,GITHUB_X_HEAD_REF,GITHUB_X_HEAD_SHA,GITHUB_REPOSITORY -Hu testbot bash -lc 'make test-go'
 
-      - name: Upload test.json
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: test-${{ matrix.platform_name }}.json
-          path: json.log
-          retention-days: 30
+  #     - name: Upload test.json
+  #       if: always()
+  #       uses: actions/upload-artifact@v4
+  #       with:
+  #         name: test-${{ matrix.platform_name }}.json
+  #         path: json.log
+  #         retention-days: 30
 
-  lint:
-    strategy:
-      matrix:
-        include:
-          - runner: ubuntu-24.04
-            image: ghcr.io/viamrobotics/rdk-devenv:amd64
-            platform: linux/amd64
-          - runner: github-linux-arm64-4core
-            image: ghcr.io/viamrobotics/rdk-devenv:arm64
-            platform: linux/arm64
-    runs-on: ${{ matrix.runner }}
-    container:
-      image: ${{ matrix.image }}
-      options: --platform ${{ matrix.platform }}
-    steps:
-      - uses: actions/checkout@v5
-        with:
-          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.event.ref }}
-      - uses: actions/setup-go@v6
-        with:
-          go-version-file: go.mod
+  # lint:
+  #   strategy:
+  #     matrix:
+  #       include:
+  #         - runner: ubuntu-24.04
+  #           image: ghcr.io/viamrobotics/rdk-devenv:amd64
+  #           platform: linux/amd64
+  #         - runner: github-linux-arm64-4core
+  #           image: ghcr.io/viamrobotics/rdk-devenv:arm64
+  #           platform: linux/arm64
+  #   runs-on: ${{ matrix.runner }}
+  #   container:
+  #     image: ${{ matrix.image }}
+  #     options: --platform ${{ matrix.platform }}
+  #   steps:
+  #     - uses: actions/checkout@v5
+  #       with:
+  #         ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.event.ref }}
+  #     - uses: actions/setup-go@v6
+  #       with:
+  #         go-version-file: go.mod
 
-      - name: Verify no uncommitted changes from "make build-go lint-go generate-go"
-        run: |
-          git init && git add .
-          make build-go lint-go generate-go
-          GEN_DIFF=$(git status -s)
-          if [ -n "$GEN_DIFF" ]; then
-              echo '"make build-go lint-go generate-go" resulted in the following untracked changes:' 1>&2
-              git diff
-              echo '"make build-go lint-go generate-go" resulted in changes not in git' 1>&2
-              git status
-              exit 1
-          fi
+  #     - name: Verify no uncommitted changes from "make build-go lint-go generate-go"
+  #       run: |
+  #         git init && git add .
+  #         make build-go lint-go generate-go
+  #         GEN_DIFF=$(git status -s)
+  #         if [ -n "$GEN_DIFF" ]; then
+  #             echo '"make build-go lint-go generate-go" resulted in the following untracked changes:' 1>&2
+  #             git diff
+  #             echo '"make build-go lint-go generate-go" resulted in changes not in git' 1>&2
+  #             git status
+  #             exit 1
+  #         fi
 
-      - name: Run CLI linter tests
-        run: go run ./cli/internal/cli_lint ./cli
+  #     - name: Run CLI linter tests
+  #       run: go run ./cli/internal/cli_lint ./cli
 
   test_win:
     name: windows
@@ -121,74 +121,73 @@ jobs:
       with:
         go-version-file: go.mod
     - name: test
-      shell: bash
       env:
         GOFLAGS: "-tags=no_cgo"
       run:
         # note: this is a subset of tests that are known to pass on windows
         go run gotest.tools/gotestsum --format standard-verbose --jsonfile json.log ./web/server
 
-    - name: Upload test.json
-      if: always()
-      uses: actions/upload-artifact@v4
-      with:
-        name: test-windows-amd64.json
-        path: json.log
-        retention-days: 30
+    # - name: Upload test.json
+    #   if: always()
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: test-windows-amd64.json
+    #     path: json.log
+    #     retention-days: 30
 
-  test32:
-    name: Go 32-bit Unit Tests
-    runs-on: ubuntu-arm-16-core
-    timeout-minutes: 30
+  # test32:
+  #   name: Go 32-bit Unit Tests
+  #   runs-on: ubuntu-arm-16-core
+  #   timeout-minutes: 30
 
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
+  #   steps:
+  #     - uses: actions/checkout@v4
+  #       with:
+  #         ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
 
-      - uses: docker/login-action@v3
-        with:
-          username: viambuild
-          password: ${{ secrets.DOCKER_PUBLIC_READONLY_PAT }}
-      - uses: docker/setup-qemu-action@v3
-      - uses: docker/setup-buildx-action@v3
+  #     - uses: docker/login-action@v3
+  #       with:
+  #         username: viambuild
+  #         password: ${{ secrets.DOCKER_PUBLIC_READONLY_PAT }}
+  #     - uses: docker/setup-qemu-action@v3
+  #     - uses: docker/setup-buildx-action@v3
 
-      - name: Run go unit tests
-        run: |
-          chmod -R a+rwx . # temporary fix for arm runners
-          docker run \
-            --platform linux/arm/v7 \
-            -v `pwd`:/rdk \
-            ghcr.io/viamrobotics/rdk-devenv:armhf-cache \
-            sudo -Hu testbot bash -lc 'sudo apt-get update && sudo apt-get install -y python3-venv && cd /rdk && go test ./...'
+  #     - name: Run go unit tests
+  #       run: |
+  #         chmod -R a+rwx . # temporary fix for arm runners
+  #         docker run \
+  #           --platform linux/arm/v7 \
+  #           -v `pwd`:/rdk \
+  #           ghcr.io/viamrobotics/rdk-devenv:armhf-cache \
+  #           sudo -Hu testbot bash -lc 'sudo apt-get update && sudo apt-get install -y python3-venv && cd /rdk && go test ./...'
 
-  motion_tests:
-    name: Test Longer-running Motion Plans if affected
-    uses: viamrobotics/rdk/.github/workflows/motion-tests.yml@main
+  # motion_tests:
+  #   name: Test Longer-running Motion Plans if affected
+  #   uses: viamrobotics/rdk/.github/workflows/motion-tests.yml@main
 
-  test_passing:
-    name: All Tests Passing
-    needs: [test_go, test32, motion_tests, test_win, lint]
-    runs-on: [ubuntu-latest]
-    if: always()
-    steps:
-      - name: Check Results
-        run: |
-          echo Go Unit Tests: ${{ needs.test_go.result }}
-          echo Go 32-bit Tests: ${{ needs.test32.result }}
-          echo Windows Tests: ${{ needs.test_win.result }}
-          echo Motion Tests: ${{ needs.motion_tests.result }}
-          echo Lint: ${{ needs.lint.result }}
-          [ "${{ needs.test_go.result }}" == "success" ] && \
-          [ "${{ needs.test32.result }}" == "success" ] && \
-          [ "${{ needs.test_win.result }}" == "success" ] && \
-          [ "${{ needs.motion_tests.result }}" == "success" ] && \
-          [ "${{ needs.lint.result }}" == "success" ]
+  # test_passing:
+  #   name: All Tests Passing
+  #   needs: [test_go, test32, motion_tests, test_win, lint]
+  #   runs-on: [ubuntu-latest]
+  #   if: always()
+  #   steps:
+  #     - name: Check Results
+  #       run: |
+  #         echo Go Unit Tests: ${{ needs.test_go.result }}
+  #         echo Go 32-bit Tests: ${{ needs.test32.result }}
+  #         echo Windows Tests: ${{ needs.test_win.result }}
+  #         echo Motion Tests: ${{ needs.motion_tests.result }}
+  #         echo Lint: ${{ needs.lint.result }}
+  #         [ "${{ needs.test_go.result }}" == "success" ] && \
+  #         [ "${{ needs.test32.result }}" == "success" ] && \
+  #         [ "${{ needs.test_win.result }}" == "success" ] && \
+  #         [ "${{ needs.motion_tests.result }}" == "success" ] && \
+  #         [ "${{ needs.lint.result }}" == "success" ]
 
-      - name: Mark appimage label
-        if: contains(github.event.pull_request.labels.*.name, 'appimage') || contains(github.event.pull_request.labels.*.name, 'appimage-ignore-tests')
-        run: echo "APPIMAGE=true" >> pr.env
+  #     - name: Mark appimage label
+  #       if: contains(github.event.pull_request.labels.*.name, 'appimage') || contains(github.event.pull_request.labels.*.name, 'appimage-ignore-tests')
+  #       run: echo "APPIMAGE=true" >> pr.env
 
-      - name: Mark static label
-        if: contains(github.event.pull_request.labels.*.name, 'static-build') || contains(github.event.pull_request.labels.*.name, 'static-ignore-tests')
-        run: echo "STATIC=true" >> pr.env
+  #     - name: Mark static label
+  #       if: contains(github.event.pull_request.labels.*.name, 'static-build') || contains(github.event.pull_request.labels.*.name, 'static-ignore-tests')
+  #       run: echo "STATIC=true" >> pr.env
